name: CI Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          cache: true
          cache-dependency-path: go.sum

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome

      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1
        id: setup-firefox

      - name: Vet
        run: go vet ./...

      - name: Run tests
        env:
          LORCACHROME: ${{ steps.setup-chrome.outputs.chrome-path }}
          LORCAFIREFOX: ${{ steps.setup-firefox.outputs.firefox-path }}
        run: go test -v -race -count=1 ./...
